# Generated by Django 5.1.15 on 2026-06-25 23:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('tables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, help_text='Reservado para multitenant en v2', null=True)),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('billing', 'Pidiendo cuenta'), ('paid', 'Pagada'), ('void', 'Anulada')], default='open', max_length=20)),
                ('diners', models.IntegerField(default=1)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('itbis', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tip', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Efectivo'), ('card', 'CardNET / Azul'), ('transfer', 'Transferencia'), ('mixed', 'Pago mixto')], max_length=20, null=True)),
                ('offline_id', models.UUIDField(blank=True, help_text='UUID del cliente para sync offline', null=True)),
                ('synced', models.BooleanField(default=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='tables.table')),
                ('waitress', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, help_text='Reservado para multitenant en v2', null=True)),
                ('name', models.CharField(max_length=200)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(default=1)),
                ('modifiers', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('preparing', 'Preparando'), ('ready', 'Listo'), ('delivered', 'Entregado')], default='pending', max_length=20)),
                ('prepared_at', models.DateTimeField(blank=True, null=True)),
                ('menu_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'verbose_name': 'Ítem de orden',
                'verbose_name_plural': 'Ítems de orden',
            },
        ),
    ]
