# Generated by Django 5.1.15 on 2026-06-26 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_amount_received_order_change_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_at',
            field=models.DateTimeField(blank=True, help_text='Cuándo pidió la cuenta', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='rnc',
            field=models.CharField(blank=True, help_text='RNC del cliente para e-CF', max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='WhatsApp del cliente para enviar e-CF', max_length=20, null=True),
        ),
    ]
