# Generated by Django 5.1.15 on 2026-06-25 23:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, help_text='Reservado para multitenant en v2', null=True)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='utensils-crossed', help_text='Nombre del ícono Lucide', max_length=50)),
                ('sort_order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, help_text='Reservado para multitenant en v2', null=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_today', models.DecimalField(blank=True, decimal_places=2, help_text='Precio del día para mariscos/precios variables', max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, help_text='Foto del plato (opcional)', upload_to='menu/')),
                ('available_today', models.BooleanField(default=True, help_text='Disponible hoy — toggle rápido sin borrar')),
                ('is_platillo_dia', models.BooleanField(default=False, help_text='Plato del día — visible destacado')),
                ('modifiers_available', models.JSONField(blank=True, default=list, help_text="Modificadores disponibles: [{'name':'sin sal','type':'toggle'}, ...]")),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.category')),
            ],
            options={
                'verbose_name': 'Producto del menú',
                'verbose_name_plural': 'Productos del menú',
                'ordering': ['category__sort_order', 'sort_order', 'name'],
            },
        ),
    ]
