# Generated by Django 5.1.15 on 2026-06-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pin',
            field=models.CharField(blank=True, help_text='PIN de 4-6 dígitos (almacenado como hash SHA-256)', max_length=128),
        ),
    ]
