# Generated by Django 5.1.15 on 2026-06-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('waitress', 'Mesera'), ('cook', 'Cocinero'), ('utility', 'Utility / Stewart'), ('owner', 'Propietario'), ('manager', 'Gerente'), ('cashier', 'Cajero'), ('bartender', 'Bartender')], default='waitress', max_length=20),
        ),
    ]
