# Generated by Django 5.1.15 on 2026-06-26 20:53

import apps.accounts.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermissions',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, help_text='Reservado para multitenant en v2', null=True)),
                ('can_void_orders', models.BooleanField(default=False)),
                ('can_apply_discount', models.BooleanField(default=False)),
                ('can_view_reports', models.BooleanField(default=False)),
                ('can_manage_menu', models.BooleanField(default=False)),
                ('can_open_cashier', models.BooleanField(default=False)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_view_all_orders', models.BooleanField(default=False)),
                ('discount_limit', models.IntegerField(default=0, help_text='Porcentaje máximo de descuento permitido [0–100]', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permisos de usuario',
                'verbose_name_plural': 'Permisos de usuario',
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, help_text='Reservado para multitenant en v2', null=True)),
                ('work_days', models.JSONField(help_text='Lista de días permitidos: 0=lunes … 6=domingo', validators=[apps.accounts.models.validate_work_days])),
                ('work_start', models.TimeField(help_text='Hora de inicio HH:MM')),
                ('work_end', models.TimeField(help_text='Hora de fin HH:MM')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedule', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Horario laboral',
                'verbose_name_plural': 'Horarios laborales',
            },
        ),
    ]
