# Generated by Django 5.1.15 on 2026-06-25 23:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ECFDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, help_text='Reservado para multitenant en v2', null=True)),
                ('ecf_type', models.CharField(choices=[('01', 'Crédito fiscal'), ('02', 'Consumidor final'), ('04', 'Nota de crédito')], default='02', max_length=2)),
                ('rnc', models.CharField(blank=True, help_text='RNC del cliente (opcional, para Tipo 01)', max_length=20)),
                ('ecf_number', models.CharField(blank=True, help_text='Número e-NCF asignado por DGII', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('failed', 'Falló')], default='pending', max_length=20)),
                ('provisional_number', models.CharField(blank=True, help_text='Número de recibo provisional (PROV-XXXX)', max_length=50)),
                ('pdf_url', models.URLField(blank=True)),
                ('qr_code', models.TextField(blank=True)),
                ('whatsapp_sent', models.BooleanField(default=False)),
                ('response_raw', models.JSONField(blank=True, default=dict, help_text='Respuesta completa del BaaS')),
                ('retries', models.IntegerField(default=0)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ecf_document', to='orders.order')),
            ],
            options={
                'verbose_name': 'Comprobante Fiscal Electrónico',
                'verbose_name_plural': 'Comprobantes Fiscales Electrónicos',
                'ordering': ['-created_at'],
            },
        ),
    ]
