# Generated by Django 5.2.15 on 2026-07-16 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_customer_deleted_at_customer_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itbis_rate', models.DecimalField(decimal_places=2, default=18.0, max_digits=5, verbose_name='ITBIS %')),
                ('tip_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Propina Legal %')),
                ('enable_tip', models.BooleanField(default=True, verbose_name='Habilitar propina legal')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de impuestos',
                'verbose_name_plural': 'Configuración de impuestos',
            },
        ),
    ]
