# Generated by Django 5.2.15 on 2026-07-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_taxconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default="D'Yiya Restaurant", max_length=200, verbose_name='Nombre del restaurante')),
                ('rnc', models.CharField(default='000000000', max_length=11, verbose_name='RNC')),
                ('address', models.CharField(blank=True, default='Samaná, República Dominicana', max_length=300, verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand/', verbose_name='Logo')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de la empresa',
                'verbose_name_plural': 'Configuración de la empresa',
            },
        ),
    ]
