# Generated by Django 5.2.16 on 2026-07-24 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_businessconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessconfig',
            name='municipio',
            field=models.CharField(blank=True, default='Samaná', max_length=100, verbose_name='Municipio'),
        ),
        migrations.AddField(
            model_name='businessconfig',
            name='provincia',
            field=models.CharField(blank=True, default='Samaná', max_length=100, verbose_name='Provincia'),
        ),
    ]
