# Generated by Django 5.2.15 on 2026-07-16 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_payment_deduct_from_payroll_payment_employee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='void_reason',
            field=models.CharField(blank=True, help_text='Motivo del reembolso', max_length=200),
        ),
        migrations.AddField(
            model_name='payment',
            name='voided',
            field=models.BooleanField(default=False, help_text='Reembolsado/Anulado'),
        ),
        migrations.AddField(
            model_name='payment',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
