# Generated by Django 5.2.15 on 2026-07-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_payment_void_reason_payment_voided_payment_voided_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuento aplicado'),
        ),
        migrations.AddField(
            model_name='payment',
            name='discount_reason',
            field=models.CharField(blank=True, max_length=100, verbose_name='Motivo del descuento'),
        ),
        migrations.AddField(
            model_name='payment',
            name='manual_tip',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Propina voluntaria extra'),
        ),
    ]
