# Generated by Django 5.2.15 on 2026-07-16 04:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0009_payment_deduct_from_payroll_payment_employee'),
        ('pos', '0005_table_x_table_y'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre descriptivo ej. "Cocina Principal"', max_length=100)),
                ('type', models.CharField(choices=[('receipt', 'Recibo (caja)'), ('kitchen', 'Comanda (cocina)'), ('bar', 'Barra')], default='receipt', max_length=10)),
                ('connection_type', models.CharField(choices=[('usb', 'USB'), ('network', 'Red (TCP/IP)'), ('file', 'Archivo (debug)')], default='network', max_length=10)),
                ('ip_address', models.CharField(blank=True, help_text='IP de la impresora de red', max_length=45)),
                ('port', models.IntegerField(default=9100, help_text='Puerto TCP (generalmente 9100)')),
                ('vendor_id', models.CharField(blank=True, help_text='Ej: 0x04b8', max_length=10)),
                ('product_id', models.CharField(blank=True, help_text='Ej: 0x0202', max_length=10)),
                ('file_path', models.CharField(blank=True, help_text='Ruta para imprimir a archivo (debug)', max_length=255)),
                ('paper_size', models.CharField(choices=[('80mm', '80mm'), ('58mm', '58mm')], default='80mm', max_length=4)),
                ('is_default', models.BooleanField(default=False, help_text='Usar por defecto para este tipo')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Impresora',
                'verbose_name_plural': 'Impresoras',
            },
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('receipt', 'Recibo de pago'), ('kitchen', 'Comanda de cocina'), ('test', 'Prueba')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('printing', 'Imprimiendo'), ('done', 'Completado'), ('failed', 'Falló')], db_index=True, default='pending', max_length=10)),
                ('data', models.JSONField(help_text='Datos completos del ticket a imprimir')),
                ('copies', models.IntegerField(default=1)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.order')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.payment')),
                ('printer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='printing.printerconfig')),
            ],
            options={
                'verbose_name': 'Trabajo de impresión',
                'verbose_name_plural': 'Trabajos de impresión',
                'ordering': ['-created_at'],
            },
        ),
    ]
