# Generated by Django 5.1.15 on 2026-06-26 20:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('void_order', 'Anulación de orden'), ('apply_discount', 'Descuento aplicado'), ('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('failed_pin', 'PIN fallido'), ('manage_user', 'Gestión de usuario'), ('open_cashier', 'Apertura de caja'), ('close_cashier', 'Cierre de caja'), ('change_price', 'Cambio de precio'), ('delete_menu_item', 'Eliminación de ítem de menú')], db_index=True, max_length=50)),
                ('actor_id', models.UUIDField(db_index=True)),
                ('actor_username', models.CharField(max_length=150)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('target_type', models.CharField(blank=True, max_length=50)),
                ('detail', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Entrada de auditoría',
                'verbose_name_plural': 'Entradas de auditoría',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action', 'timestamp'], name='audit_action_ts_idx')],
            },
        ),
    ]
