# Generated by Django 5.2.15 on 2026-07-06 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_menuitem_price_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='table',
            name='y',
            field=models.FloatField(default=0.0),
        ),
    ]
