# Generated by Django 5.2.15 on 2026-07-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_table_x_table_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
    ]
