# Generated by Django 5.1.15 on 2026-06-25 23:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, help_text='Reservado para multitenant en v2', null=True)),
                ('supplier_rnc', models.CharField(help_text='RNC del proveedor', max_length=20)),
                ('supplier_name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('ncf', models.CharField(help_text='NCF o e-CF del proveedor', max_length=50)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('itbis', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras (606)',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
